export * as authService from './authService.js'
export * as patientsService from './patientsService.js'
export * as dashboardService from './dashboardService.js'
export * as assessmentsService from './assessmentsService.js'
export * as evolutionsService from './evolutionsService.js'
export * as photosService from './photosService.js'
export * as prescriptionsService from './prescriptionsService.js'
export * as monitoringService from './monitoringService.js'
export * as reportsService from './reportsService.js'
export * as stockService from './stockService.js'
export * as agendaService from './agendaService.js'
export * as settingsService from './settingsService.js'
export * as documentsService from './documentsService.js'
export { apiClient, isApiConfigured } from './apiClient.js'
