import { useEffect,useState } from 'react';
import { Plus, Package, ArrowDownToLine, ArrowUpFromLine, AlertTriangle } from 'lucide-react';
import { AppShell } from "../../components/AppShell/AppShell";
import { getStockItems,getStockAlerts,createStockItem,addStockMovement } from '../../services/api';
import '../Module.css';
export default function Estoque(){
 const [items,setItems]=useState([]),[alerts,setAlerts]=useState([]),[show,setShow]=useState(false),[move,setMove]=useState(null),[error,setError]=useState('');
 async function load(){try{const [i,a]=await Promise.all([getStockItems(),getStockAlerts()]);setItems(i);setAlerts(a)}catch(e){setError(e.message)}} useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();const f=new FormData(e.target);try{await createStockItem({name:f.get('name'),unit:f.get('unit'),quantity:Number(f.get('quantity')||0),min_quantity:Number(f.get('min_quantity')||0),expiry_date:f.get('expiry_date')||null,unit_cost:Number(f.get('unit_cost')||0),category:f.get('category')});setShow(false);load()}catch(e){setError(e.message)}}
 async function movement(e){e.preventDefault();const f=new FormData(e.target);try{await addStockMovement({item_id:move.id,direction:f.get('direction'),quantity:Number(f.get('quantity')),reason:f.get('reason')});setMove(null);load()}catch(e){setError(e.message)}}
 return <AppShell title="Estoque" subtitle="Controle materiais, consumo e alertas de reposição.">
  <div className="metric-grid"><div className="module-card"><span className="metric-label">Itens ativos</span><div className="metric">{items.length}</div><Package size={18}/></div><div className="module-card"><span className="metric-label">Alertas</span><div className="metric negative">{alerts.length}</div><AlertTriangle size={18}/></div><div className="module-card"><span className="metric-label">Categorias</span><div className="metric">{new Set(items.map(i=>i.category).filter(Boolean)).size}</div></div></div>
  <div className="page-toolbar"><h2 className="section-small">Materiais cadastrados</h2><button className="action-btn" onClick={()=>setShow(true)}><Plus size={17}/> Novo item</button></div>{error&&<div className="toast-error">{error}</div>}
  <div className="data-card">{items.length===0?<div className="empty-module"><Package size={34}/><h3>Estoque vazio</h3><p>Cadastre materiais para acompanhar o consumo.</p></div>:<table className="data-table"><thead><tr><th>Item</th><th>Categoria</th><th>Quantidade</th><th>Mínimo</th><th>Validade</th><th>Ações</th></tr></thead><tbody>{items.map(i=>{const low=Number(i.quantity)<=Number(i.min_quantity);return <tr key={i.id}><td><b>{i.name}</b><div className="muted">{i.unit}</div></td><td>{i.category||'—'}</td><td><span className={`pill ${low?'danger':''}`}>{Number(i.quantity).toLocaleString('pt-BR')} {i.unit}</span></td><td>{Number(i.min_quantity).toLocaleString('pt-BR')}</td><td>{i.expiry_date?new Date(i.expiry_date).toLocaleDateString('pt-BR'):'—'}</td><td><div className="row-actions"><button className="mini-btn" title="Entrada" onClick={()=>setMove({...i,dir:'in'})}><ArrowDownToLine size={15}/></button><button className="mini-btn" title="Saída" onClick={()=>setMove({...i,dir:'out'})}><ArrowUpFromLine size={15}/></button></div></td></tr>})}</tbody></table>}</div>
  {show&&<div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="modal-head"><h2>Novo item</h2><button type="button" onClick={()=>setShow(false)}>×</button></div><div className="form-grid"><div className="form-field full"><label>Nome</label><input name="name" placeholder="Ex.: Gaze estéril" required/></div><div className="form-field"><label>Unidade</label><select name="unit"><option value="un">Unidade</option><option value="cm">cm</option><option value="ml">ml</option><option value="g">g</option></select></div><div className="form-field"><label>Quantidade inicial</label><input name="quantity" type="number" step="0.01" min="0" defaultValue="0"/></div><div className="form-field"><label>Estoque mínimo</label><input name="min_quantity" type="number" step="0.01" min="0" defaultValue="0"/></div><div className="form-field"><label>Custo unitário</label><input name="unit_cost" type="number" step="0.01" min="0"/></div><div className="form-field"><label>Categoria</label><select name="category"><option value="dressing">Curativo</option><option value="medication">Medicamento</option><option value="equipment">Equipamento</option><option value="consumable">Consumível</option></select></div><div className="form-field"><label>Validade</label><input name="expiry_date" type="date"/></div></div><div className="form-actions"><button type="button" className="ghost-btn" onClick={()=>setShow(false)}>Cancelar</button><button className="action-btn">Cadastrar item</button></div></form></div>}
  {move&&<div className="modal-backdrop"><form className="modal-card" onSubmit={movement}><div className="modal-head"><h2>{move.dir==='in'?'Entrada':'Saída'} de estoque</h2><button type="button" onClick={()=>setMove(null)}>×</button></div><p className="modal-desc"><b>{move.name}</b> · saldo atual {Number(move.quantity)} {move.unit}</p><div className="form-field"><label>Quantidade</label><input name="quantity" type="number" step="0.01" min="0.01" required/></div><div className="form-field"><label>Motivo</label><input name="reason" placeholder="Compra, uso clínico..." /></div><div className="form-actions"><button type="button" className="ghost-btn" onClick={()=>setMove(null)}>Cancelar</button><button className="action-btn">Registrar</button></div></form></div>}
 </AppShell>
}
