spring.application.name=revigorar-backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/revigorar
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true