import { useEffect,useState } from 'react';
import { Plus, DollarSign, ArrowUpRight, ArrowDownRight, Trash2 } from 'lucide-react';
import { AppShell } from "../../components/AppShell/AppShell";
import { getFinancialDashboard,getFinancialRecords,createFinancialRecord,deleteFinancialRecord } from '../../services/api';
import '../Module.css';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function Financeiro(){
 const [dash,setDash]=useState({income:0,expense:0,profit:0}),[records,setRecords]=useState([]),[show,setShow]=useState(false),[error,setError]=useState('');
 async function load(){try{const [d,r]=await Promise.all([getFinancialDashboard(),getFinancialRecords('limit=100')]);setDash(d);setRecords(r.data||[])}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();const f=new FormData(e.target);try{await createFinancialRecord({type:f.get('type'),category:f.get('category'),amount:Number(f.get('amount')),description:f.get('description'),payment_method:f.get('payment_method'),recorded_date:f.get('recorded_date')});setShow(false);load()}catch(e){setError(e.message)}}
 async function remove(id){if(!confirm('Excluir este lançamento?'))return;try{await deleteFinancialRecord(id);load()}catch(e){setError(e.message)}}
 return <AppShell title="Financeiro" subtitle="Acompanhe receitas, despesas e o resultado da sua prática.">
 <div className="metric-grid"><div className="module-card"><span className="metric-label">Receita</span><div className="metric positive">{money(dash.income)}</div><ArrowUpRight size={18}/></div><div className="module-card"><span className="metric-label">Despesas</span><div className="metric negative">{money(dash.expense)}</div><ArrowDownRight size={18}/></div><div className="module-card"><span className="metric-label">Lucro líquido</span><div className="metric">{money(dash.profit)}</div><DollarSign size={18}/></div></div>
 <div className="page-toolbar"><h2 className="section-small">Lançamentos</h2><button className="action-btn" onClick={()=>setShow(true)}><Plus size={17}/> Novo lançamento</button></div>
 {error&&<div className="toast-error">{error}</div>}
 <div className="data-card">{records.length===0?<div className="empty-module"><DollarSign size={34}/><h3>Nenhum lançamento</h3><p>Registre sua primeira entrada ou despesa.</p></div>:<table className="data-table"><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Forma</th><th>Valor</th><th></th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{new Date(r.recorded_date).toLocaleDateString('pt-BR')}</td><td><b>{r.description||'Sem descrição'}</b><div className="muted">{r.type==='income'?'Entrada':'Saída'}</div></td><td>{r.category}</td><td>{r.payment_method||'—'}</td><td className={r.type==='income'?'money-in':'money-out'}>{r.type==='income'?'+':'-'} {money(r.amount)}</td><td><button className="mini-btn danger-mini" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>}</div>
 {show&&<div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="modal-head"><h2>Novo lançamento</h2><button type="button" onClick={()=>setShow(false)}>×</button></div><div className="form-grid"><div className="form-field"><label>Tipo</label><select name="type"><option value="income">Entrada</option><option value="expense">Despesa</option></select></div><div className="form-field"><label>Valor</label><input name="amount" type="number" step="0.01" min="0.01" required/></div><div className="form-field"><label>Categoria</label><select name="category"><option value="consultation">Consulta</option><option value="materials">Materiais</option><option value="rent">Aluguel</option><option value="transport">Transporte</option><option value="other">Outro</option></select></div><div className="form-field"><label>Forma de pagamento</label><select name="payment_method"><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit">Crédito</option><option value="debit">Débito</option><option value="transfer">Transferência</option></select></div><div className="form-field"><label>Data</label><input name="recorded_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="form-field full"><label>Descrição</label><input name="description" placeholder="Ex.: Consulta de retorno"/></div></div><div className="form-actions"><button type="button" className="ghost-btn" onClick={()=>setShow(false)}>Cancelar</button><button className="action-btn">Salvar lançamento</button></div></form></div>}
 </AppShell>
}
